theme: jekyll-theme-minimal
title: Bojiang Li
description: 
"Incoming MSMITE candidate at Carnegie Mellon University.
Bachalor of Science at University of Illinois at Urbana-Champaign."
show_downloads: false
